import os from "os";

// Historial Global para chatbot
export let conversationHistory = [];

// Obtener cantidad de nucleos del proce
export const numCpus = os.cpus().length; 

// Maxima cantidad de interraciones entre user y chatbot
export const MAX_MESSAGES = 10; // recordar que es x2 los mensajes, los del usuario + chatbot

// frases legibles (puedes editar/agregar)
export const AMBIGUOUS_QUERIES = [
  "tienen más opciones",
  "tienen mas opciones",
  "tienen otras opciones",
  "tienes más opciones",
  "tienes mas opciones",
  "tienes otras opciones",
  "muéstrame otra opción",
  "muéstrame otra",
  "muéstrame otras opciones",
  "mostrar más",
  "mostrar mas",
  "mostrar más productos",
  "mostrar mas productos",
  "ver más",
  "ver mas",
  "dame más opciones",
  "dame mas opciones",
  "dame otra opción",
  "dame otras opciones",
  "qué más tienen",
  "que más tienen",
  "qué más hay",
  "que más hay",
  "qué más ofrecen",
  "que más ofrecen",
  "más alternativas",
  "mas alternativas",
  "otra opción",
  "otro producto",
  "otra alternativa",
  "otra marca",
  "otra variante",
  "otros modelos",
  "otras variedades",
  "más modelos",
  "mas modelos",
  "más colores",
  "mas colores",
  "más tamaños",
  "mas tamaños",
  "otra cosa",
  "otra cosa parecida",
  "algo más",
  "algo distinto",
  "algo diferente",
  "algo parecido",
  "tienen algo parecido",
  "tienes algo parecido",
  "tienen algo similar",
  "tienes algo similar",
  "no es lo que busco",
  "no eso",
  "no me convence",
  "no me gusta",
  "no es lo que quiero",
  "otro tipo",
  "otro tipo de producto",
  "otras sugerencias",
  "sugerencias",
  "recomiéndame algo más",
  "recomiendame algo mas",
  "otra recomendación",
  "otra recomendacion",
  "continúa",
  "continuar",
  "sigue",
  "siguiente",
  "enséñame más",
  "enseñame más",
  "enseñame otras opciones",
  "enseñame otras"
];

