name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar SSH
      - name: Setup SSH for deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.VPS_PORT }}" -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.VPS_PORT }}

      # 3️⃣ Sincronizar archivos con rsync
      - name: Rsync files to VPS
        run: |
          rsync -avz --delete --exclude=".git" --exclude="node_modules" \
          -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.VPS_PORT }}" \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/app/dwight_IA/
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PORT: ${{ secrets.VPS_PORT }}

      # 4️⃣ Instalar dependencias y reiniciar app
      - name: Install deps & restart on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            # Cargar NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Ir al directorio de la app
            cd /home/${USER}/app/dwight_IA || exit 1

            # Instalar dependencias
            npm install --production

            # Descomenta si necesitas build para Next.js
            # npm run build

            # Reiniciar o iniciar app con PM2
            if pm2 describe dwightIA > /dev/null; then
              pm2 reload dwightIA
            else
              pm2 start npm --name "dwightIA" -- start
            fi

            exit
          EOF
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
